CALL THE MAIN FUNCTION ERRORS -  Need quotes arount my_name.txt and name to file needs to be myfile.write
Cell In[15], line 20
     18 # Call the main function
     19 if __name__ == '__main__':
---> 20     main()

Cell In[15], line 6, in main()
      3 your_name = 'Joshua Yerian'
      5 # filename
----> 6 filename = my_name.txt
      8 # Open the file in write mode
      9 myfile = open('my_name.txt', 'w')

NameError: name 'my_name' is not defined